print("This program is designed to calculate love % of you and your partner. ")
game=input("Do you want to play this game?: (Y/N): ")
print(" ")
print(" ")
if game == 'Y' or game == 'y' or game == 'YES' or game == 'Yes' or game == 'yes':
	y_n=input("What is your full name?: ")
	p_n=input("Type your partner full name: ")
	name= y_n+p_n
	l_n=name.lower()
	t = l_n.count('t')
	r = l_n.count('r')
	u = l_n.count('u')
	e = l_n.count('e')
	l = l_n.count('l')
	o = l_n.count('o')
	v = l_n.count('v')
	first_digit = t+r+u+e
	second_digit = l+o+v+e
	love_meter= str(first_digit)+str(second_digit)
	print(" ")
	print(" ")
	print(f" Your love meter score is {love_meter}%. ")
	print(" ")
	print(" ")
	print(" ")
	print("Disclaimer:-\n The Love Meter game is intended for entertainment purposes only. The results generated by the game are based on a random algorithm and do not reflect any scientific, psychological, or astrological validity. The game should not be used as a basis for making decisions regarding relationships or personal matters.By playing the Love Meter game, you acknowledge that:\n \n •The results are purely fictional and should not be taken seriously.\n •The game is not a substitute for professional advice or counseling.\n •The creators of the Love Meter game are not responsible for any actions taken based on the game's results.\n \n Enjoy the game and have fun, but always remember to approach love and relationships with thoughtfulness and care. ")
elif game == 'N' or game == 'n' or game == 'NO' or game == 'No' or game == 'no':
		print("Ok, please visit again. ")
else:
	print("Wrong input please try again. ")

	